# This is a placeholder hardware configuration file.
# During NixOS installation, this file will be auto-generated by nixos-generate-config
# and will contain your specific hardware configuration.
#
# IMPORTANT: Replace this file with the generated one during installation!

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # This is a placeholder - the actual configuration will be generated during installation
  # It will include:
  # - Boot loader configuration
  # - Filesystem mounts
  # - Network interfaces
  # - Hardware-specific settings

  # Placeholder filesystem configuration (will be replaced)
  fileSystems."/" = {
    device = "/dev/disk/by-label/NixOS";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/EFI";
    fsType = "vfat";
  };

  # Swap configuration (if applicable)
  swapDevices = [ ];

  # Networking
  networking.useDHCP = lib.mkDefault true;

  # CPU
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Hardware support
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
